### ISSUE TITLE
Old url in a screen

### ISSUE THREAD

**Issue by rgarrigue** [LycheeOrg/LycheeOrg.github.io#1]
Hello

Just looking around Lychee since it moved, I saw that you updated the first screenshot with the new url, but the gif below is still on the old url

![image](https://user-images.githubusercontent.com/1872031/45947843-06199500-bff6-11e8-8ac6-d172398c1ded.png)

Good luck with the fork :-)

**Comment by ildyria** [comment]
Solved. :)
