### ISSUE TITLE
The demo site still uses Lychee-3.2.8

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/LycheeOrg.github.io#11]
Go to https://lycheeorg.github.io/demo/
Try to login. You get "Lychee 3.2.8 - Update available"

**Comment by ildyria** [comment]
Yeah. I need to regenerate it.

**Comment by VictorLamoine** [comment]
Ping, you should demonstrate v4 now

**Comment by ildyria** [comment]
> Yeah. I need to regenerate it.

oupsie.

**Comment by ildyria** [comment]
done.
