### ISSUE TITLE
Upgrade via git, git pull vs fetch?

### ISSUE THREAD

**Issue by privong** [LycheeOrg/LycheeOrg.github.io#16]
Currently the documentation for upgrades (https://lycheeorg.github.io/docs/update.html) recommends `git pull` to bring things to the latest version. But this will bring Lychee up to `HEAD`, which may be ahead of a given release.

It seems it would be preferable for new commits to be `fetch`'ed and then have the user check out the release by tag name. I.e.,:

```
git fetch
git checkout v4.0.6
```

This would ensure that users are running tagged releases rather than on some random commit to master. It may make it easier to debug potential issues.

**Comment by privong** [comment]
Also, I wasn't sure if documentation-related questions were best listed here, or in the main software repo. Happy to re-post the issue over there if it's more appropriate.

**Comment by d7415** [comment]
We consider master stable for Lychee - we don't have any special process to check a release, it happens for every commit. As such we generally recommend users who are comfortable with git (or our upgrade UI) to use master. Our Diagnostics output (that's required for issues) tells us which commit is in use, if applicable.

As for which repo, I'd lean towards the main Lychee repo except for PRs. I'm not sure about @ildyria's views.

Thanks for the interest though. There may be some benefit to having that as an alternative in the docs, but they're getting a bit busy. I'll hand that off again to @ildyria and leave this open until he's had his 2c.

**Comment by privong** [comment]
Makes sense. Thanks! I'll keep this issue open pending the discussion on where to submit docs issues.

**Comment by ildyria** [comment]
Issues for the docs are welcome here. :)
