### ISSUE TITLE
New Server For Live Demo Needed

### ISSUE THREAD

**Issue by SabrinaFinkel** [LycheeOrg/LycheeOrg.github.io#5]
The old live demo on [https://ld.electerious.com/](https://ld.electerious.com/) by @electerious is not working anymore. Can someone create a new Lychee live demo please?

**Comment by d7415** [comment]
Removed the link (Hopefully temporarily). I'll look at adding a live demo unless someone beats me to it.

**Comment by ildyria** [comment]
I managed to create a demo at https://lycheeorg.github.io/demo/ : I just hooked the `api.post` function. :D
See here: https://github.com/LycheeOrg/LycheeOrg.github.io/blob/master/demo/dist/main.js#L1166

**Comment by ildyria** [comment]
I will give it a try when I have some time. :)

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 29 déc. 2018 à 14:22, à 14:22, Ludovic Rousseau <notifications@github.com> a écrit:

**Comment by SabrinaFinkel** [comment]
Awesome @ildyria, thank you so much! 😎
